// <auto-generated />
namespace SVI.Recibo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class versao_1_0_0_0 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(versao_1_0_0_0));
        
        string IMigrationMetadata.Id
        {
            get { return "201805081914118_versao_1_0_0_0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
